---
- hosts: all
  become: yes
  tasks:
    - name: Install apache
      apt:
        name: apache2
        update_cache: yes

    - name: Install mysql-server
      apt:
        name: mysql-server
        update_cache: yes

    - name: Install PHP
      apt:
        name: php
        update_cache: yes

    - name: Install libapache2-mod-php
      apt:
        name: libapache2-mod-php
        update_cache: yes

    - name: Install php-mysql
      apt:
        name: php-mysql
        update_cache: yes
