- name: Docker Installation
  service:
    name: Docker
    state: started
    enabled: yes

- name: web server
  docker_image:
    name: newdeveloper/apache-php
    state: present
    source: pull

- name: db server
  docker_image:
    name: mysql/mysql-server:latest
    state: present
    source: pull


