- name: Install NTP
  yum:
    name: chrony
    state: latest

- name: edit chrony daemon
  lineinfile:
    path: /etc/chrony.conf
    regexp: '^allow 192.168.0.0/16'
    line: allow 192.168.0.0/24

- name: edit chrony daemon
  lineinfile:
    path: /etc/chrony.conf
    line: 'service controller burst'

- name: starting chronyd service
  service:
    name: chronyd
    state: started
    enabled: yes


