galaxy_info:
  author: your name
  description: your role description
  company: your company (optional)

  license: license (GPL-2.0-or-late, MIT, etc)

  main_ansible_version: 2.9

  galaxy_tags: []

  dependencies: []


