- name: Download Dependencies
  apt:
    name: apt-transport-https
    update_cache: yes

- name: Getting GPG key
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Adding to repo
  ansible.builtin.apt_repository:
    repo: deb https://artifacts.elastic.co/packages/8.x/apt stable main
    state: present

- name: Installing Elastic Stack
  apt:
    pkg:
      - elasticsearch
      - kibana
      - logstash
      - filebeat
      - nginx
    update_cache: yes
